// Generated by CoffeeScript 1.9.2
(function() {
  self.addEventListener('push', function(e) {
    var body, data, icon, showNotification, title;
    console.log("push message received");
    console.log("hello");
    title = 'a';
    body = 'b';
    icon = 'c';
    data = 'd';
    showNotification = function(title, body, icon, data) {
      var notificationOptions;
      notificationOptions = {
        body: body,
        icon: 'images/touch/chrome-touch-icon-192x192.png',
        tag: 'simple-push-demo-notification',
        data: data
      };
      if (self.registration.showNotification) {
        self.registration.showNotification(title, notificationOptions);
        return 0;
      } else {
        return new Notification(title, notificationOptions);
      }
    };
    showNotification(title, body, icon, data);
  });

}).call(this);


//# sourceMappingURL=sw1.js.map
