// Generated by CoffeeScript 1.9.2
(function() {
  if (!navigator.serviceWorker) {
    return;
  }

  navigator.serviceWorker.register('./sw.js', {
    scope: './'
  }).then(function() {
    if (!PushManager) {
      return;
    }

    /*
    We have already checked that the browser supports serviceworker and
    push notifications. Now we can subscribe for push notifications from GCM
    and obtain the endpoints and the subscription ID.
     */
    return navigator.serviceWorker.ready.then(function(serviceWorkerRegistration) {
      return serviceWorkerRegistration.pushManager.subscribe({
        userVisibleOnly: true
      }).then(function(subscriptionDetails) {
        console.log(subscriptionDetails);
      })["catch"](function(e) {
        if (navigator.permissions) {
          navigator.permissions.query({
            name: 'push',
            userVisibleOnly: true
          }).then(function(permissionStatus) {
            return navigator.serviceWorker.ready.then(function(serviceWorkerRegistration) {
              return serviceWorkerRegistration.pushManager.getSubscription().then(function(subscription) {
                if (!subscription) {
                  console.log('no subscription');
                  return;
                }
                console.log(subscription);
              });
            });
          });
        }
      });
    });
  });

}).call(this);


//# sourceMappingURL=main.js.map
